#!/bin/sh

# CAM
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/cam/bld/namelist_files/namelist_definition.xml --comp CAM --htmlfile /cesmweb/html/models/cesm2/component_settings/cam_nml.html --comptag cam_cesm2_0_rel_02 --compversion 6.0

# DATM
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/components/data_comps/datm/cime_config/namelist_definition_datm.xml --comp DATM --htmlfile /cesmweb/html/models/cesm2/component_settings/datm_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# CLM
# had to remove one & manually in input namelist file for clm4_5
# also desc elements, need to be pre formatted in order to wrap correctly in the data table
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/clm/bld/namelist_files/namelist_definition_clm4_5.xml --comp CLM --htmlfile /cesmweb/html/models/cesm2/component_settings/clm4_5_nml.html --comptag release-clm5.0.0
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/clm/bld/namelist_files/namelist_definition_clm4_0.xml --comp CLM --htmlfile /cesmweb/html/models/cesm2/component_settings/clm4_0_nml.html --comptag clm4.0.81

# DLND
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/components/data_comps/dlnd/cime_config/namelist_definition_dlnd.xml --comp DLND --htmlfile /cesmweb/html/models/cesm2/component_settings/dlnd_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# MOSART
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/mosart/cime_config/namelist_definition_mosart.xml --comp MOSART --htmlfile /cesmweb/html/models/cesm2/component_settings/mosart_nml.html --comptag release-cesm2.0.00

# RTM
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/rtm/cime_config/namelist_definition_rtm.xml --comp RTM --htmlfile /cesmweb/html/models/cesm2/component_settings/rtm_nml.html --comptag release-cesm2.0.00

# DLND
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/components/data_comps/drof/cime_config/namelist_definition_drof.xml --comp DROF --htmlfile /cesmweb/html/models/cesm2/component_settings/drof_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# POP2
# pop namelist required *a lot* of manual edits to get it parse through CIME tools and namelist_defaults.xml is kinda hopeless
./nmldef2html.py --nmlfile ~/CESM_xml2html/pop_namelist_files/namelist_definition_pop.xml --comp POP2 --htmlfile /cesmweb/html/models/cesm2/component_settings/pop2_nml.html --comptag pop2_cesm2_0_rel_n02

# DOCN
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/components/data_comps/docn/cime_config/namelist_definition_docn.xml --comp DOCN --htmlfile /cesmweb/html/models/cesm2/component_settings/docn_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# CICE
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/cice/cime_config/namelist_definition_cice.xml --comp CICE --htmlfile /cesmweb/html/models/cesm2/component_settings/cice_nml.html --comptag cice5_cesm2_0_rel_01 --compversion 5.0

# DICE
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/components/data_comps/dice/cime_config/namelist_definition_dice.xml --comp DICE --htmlfile /cesmweb/html/models/cesm2/component_settings/dice_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# WW3
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/ww3/cime_config/namelist_definition_ww3.xml --comp WW3 --htmlfile /cesmweb/html/models/cesm2/component_settings/ww3_nml.html --comptag ww3_cesm2_0_rel_01

# DWAV
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/components/data_comps/dwav/cime_config/namelist_definition_dwav.xml --comp DWAV --htmlfile /cesmweb/html/models/cesm2/component_settings/dwav_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# CISM
./nmldef2html.py --nmlfile /home/aliceb/cesm/components/cism/bld/namelist_files/namelist_definition_cism.xml --comp CISM --htmlfile /cesmweb/html/models/cesm2/component_settings/cism_nml.html --comptag release-cesm2.0.01

# Driver
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/drivers/mct/cime_config/namelist_definition_drv.xml --comp Driver --htmlfile /cesmweb/html/models/cesm2/component_settings/drv_nml.html --comptag cime_cesm2_0_rel_03
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/drivers/mct/cime_config/namelist_definition_drv_flds.xml --comp Driver --htmlfile /cesmweb/html/models/cesm2/component_settings/drv_fields_nml.html --comptag cime_cesm2_0_rel_03

# DESP
./nmldef2html.py --nmlfile /home/aliceb/cesm/cime/src/components/data_comps/desp/cime_config/namelist_definition_desp.xml --comp DESP --htmlfile /cesmweb/html/models/cesm2/component_settings/desp_nml.html --comptag cime_cesm2_0_rel_03 --compversion 2.0
