#!/bin/sh

# CAM
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/cam/cime_config/config_component.xml --comp CAM --htmlfile /cesmweb/html/models/cesm2/component_settings/cam_input.html --comptag cam_cesm2_0_rel_02 --compversion 6.0

# DATM
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/components/data_comps/datm/cime_config/config_component.xml --comp DATM --htmlfile /cesmweb/html/models/cesm2/component_settings/datm_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# CLM - not sure how to handle CLM4.0 since it wasn't a CIME compliant model and doesn't have a unique config_component.xml file
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/clm/cime_config/config_component.xml --comp CLM --htmlfile /cesmweb/html/models/cesm2/component_settings/clm4_5_input.html --comptag release-clm5.0.0
#./compinputdef2html.py --inputfile /home/aliceb/cesm/components/clm/cime_config/??? --comp CLM --htmlfile /cesmweb/html/models/cesm2/component_settings/clm4_0_input.html --comptag clm4.0.81

# DLND
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/components/data_comps/dlnd/cime_config/config_component.xml --comp DLND --htmlfile /cesmweb/html/models/cesm2/component_settings/dlnd_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# MOSART
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/mosart/cime_config/config_component.xml --comp MOSART --htmlfile /cesmweb/html/models/cesm2/component_settings/mosart_input.html --comptag release-cesm2.0.00

# RTM
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/rtm/cime_config/config_component.xml --comp RTM --htmlfile /cesmweb/html/models/cesm2/component_settings/rtm_input.html --comptag release-cesm2.0.00

# DROF
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/components/data_comps/drof/cime_config/config_component.xml --comp DROF --htmlfile /cesmweb/html/models/cesm2/component_settings/drof_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# POP2
# pop namelist required *a lot* of manual edits to get it parse through CIME tools and namelist_defaults.xml is kinda hopeless
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/pop/cime_config/config_component.xml --comp POP2 --htmlfile /cesmweb/html/models/cesm2/component_settings/pop2_input.html --comptag pop2_cesm2_0_rel_n02

# DOCN - required a tweek to the "QOBS" string in DOCN_MODE desc because the quotes were invalid ascii characters
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/components/data_comps/docn/cime_config/config_component.xml --comp DOCN --htmlfile /cesmweb/html/models/cesm2/component_settings/docn_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# CICE
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/cice/cime_config/config_component.xml --comp CICE --htmlfile /cesmweb/html/models/cesm2/component_settings/cice_input.html --comptag cice5_cesm2_0_rel_01 --compversion 5.0

# DICE
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/components/data_comps/dice/cime_config/config_component.xml --comp DICE --htmlfile /cesmweb/html/models/cesm2/component_settings/dice_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# WW3
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/ww3/cime_config/config_component.xml --comp WW3 --htmlfile /cesmweb/html/models/cesm2/component_settings/ww3_input.html --comptag ww3_cesm2_0_rel_01

# DWAV
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/components/data_comps/dwav/cime_config/config_component.xml --comp DWAV --htmlfile /cesmweb/html/models/cesm2/component_settings/dwav_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0

# CISM
./compinputdef2html.py --inputfile /home/aliceb/cesm/components/cism/cime_config/config_component.xml --comp CISM --htmlfile /cesmweb/html/models/cesm2/component_settings/cism_input.html --comptag release-cesm2.0.01

# Driver
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/drivers/mct/cime_config/config_component.xml --comp Driver --htmlfile /cesmweb/html/models/cesm2/component_settings/drv_input.html --comptag cime_cesm2_0_rel_03
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/drivers/mct/cime_config/config_component_cesm.xml --comp Driver --htmlfile /cesmweb/html/models/cesm2/component_settings/drv_input_cesm.html --comptag cime_cesm2_0_rel_03

# DESP
./compinputdef2html.py --inputfile /home/aliceb/cesm/cime/src/components/data_comps/desp/cime_config/config_component.xml --comp DESP --htmlfile /cesmweb/html/models/cesm2/component_settings/desp_input.html --comptag cime_cesm2_0_rel_03 --compversion 2.0
